version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev-db
    ports:
      - "5432:5432"
    # volumes:
      # - ./path/to/custom/postgresql.conf:/etc/postgresql/postgresql.conf # Add if you need custom config
    command: ["postgres", "-c", "max_connections=200"]

